#!/usr/bin/env bash
# redirecting http request
red="server {
\n\t	listen 80;
\n\t	rewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
\n}"
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sed -i -e '$aserver {' /etc/nginx/sites-available/default
sed -i -e '$a	rewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sed -i -e '$a}' /etc/nginx/sites-available/default
service nginx star
