#!/usr/bin/env bash
# redirecting http request
red='server {
	listen 80;
	rewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
}'
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sed -e -i $red /etc/nginx/sites-available/default
service nginx star
