#!/usr/bin/env bash
# redirecting http request
red="server {
\n\t	listen 80;
\n\t	rewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
\n}"
echo -e $red >> /etc/nginx/sites-available/default
