#!/usr/bin/env bash
# redirecting http request
sed -i -e '$aserver {' /etc/nginx/sites-available/default
sed -i -e '$a	rewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sed -i -e '$a}' /etc/nginx/sites-available/default
