#!/usr/bin/env bash
# installs load balancer
apt-get update
apt-get install software-properties-common -y
add-apt-repository ppa:vbernat/haproxy-1.7 -y
apt-get update
apt-get install haproxy=1.7.\* -y
echo "frontend web-front
        bind *:80
        default_backend web-backend
backend web-backend
        balance roundrobin
        server web1 3.238.106.249:80 check
        server web2 3.239.115.217:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
