#!/usr/bin/env bash
#creates a backup for a database
name=`date +"%d-%m-%Y"`
filename="$name"
filename+=".tar.gz"
sudo mysqldump -u root tyrell_corp -p "$1" > backup.sql
gzip -c backup.sql > "$filename"

