#!/usr/bin/env bash
# make ubuntu container run

string="server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /usr/share/nginx/html;
		index index.html index.htm index.nginx-debian.html;
	# Make site accessible from http://localhost/
	server_name localhost;

	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
	}
}"
echo -e "$string" > /etc/nginx/sites-enabled/default
service nginx restart
