#!/usr/bin/env bash
# Bash script that displays Best School 10 times.
n=10
while [ "$n" -ne 0 ] 
do
	if [ "$n" -eq 4 ]
	then
		echo bad luck
	else
		if [ "$n" -eq 8 ]
		then
			echo good luck
		else
			echo Best School
		fi
	fi
	(( n-- ))
done
