#!/usr/bin/env bash
# Bash script that displays Best School 10 times.
n=1
while [ "$n" -ne 21 ] 
do
	echo "$n"
	case "$n" in
		4)
			echo bad luck from China
			;;
		9)
			echo bad luck from Japan
			;;
		17)
			echo bad luck from Italy
			;;
	esac
	(( n++ ))
done
